sonata_admin:
    extensions:
        cmf_core.admin_extension.child:
            implements:
                - Symfony\Cmf\Bundle\CoreBundle\Model\ChildInterface
        cmf_core.admin_extension.publish_workflow.time_period:
            implements:
                - Symfony\Cmf\Bundle\CoreBundle\PublishWorkflow\PublishTimePeriodInterface
        cmf_core.admin_extension.publish_workflow.publishable:
            implements:
                - Symfony\Cmf\Bundle\CoreBundle\PublishWorkflow\PublishableInterface
        cmf_menu.admin_extension.menu_node_referrers:
            implements:
                - Symfony\Cmf\Bundle\MenuBundle\Model\MenuNodeReferrersInterface
        cmf_menu.admin_extension.menu_options:
            implements:                
                - Symfony\Cmf\Bundle\MenuBundle\Model\MenuOptionsInterface
        cmf_routing.admin_extension.route_referrers:
            implements:
                - Symfony\Cmf\Component\Routing\RouteReferrersInterface
        cmf_seo.admin_extension:
            implements:
                - Symfony\Cmf\Bundle\SeoBundle\SeoAwareInterface
        nvbooster_starter.admin_extension.settings:
            implements:
                - Sonata\BlockBundle\Model\BlockInterface
        nvbooster_starter.admin_extension.sitemap_parameters:
            implements:
                - nvbooster\StarterBundle\Sitemap\SitemapPropertiesInterface

    dashboard:
        blocks:
            - { position: right, type: sonata.admin.block.admin_list }
            - { position: left, type: sonata_admin_doctrine_phpcr.tree_block }
        groups:
            content:
                label: Content
                items:
                    - cmf_content.admin
                    - cmf_block.simple_admin
                    - cmf_block.string_admin
                    - cmf_block.container_admin
                    - cmf_block.reference_admin
                    - cmf_block.action_admin
                    - nvbooster_starter.rssblock_admin
                    - cmf_block.imagine.slideshow_admin
                    - cmf_block.imagine.imagine_admin
                    - nvbooster_starter.unitblock_admin
            routing:
                label: URLs
                items:
                    - cmf_routing.route_admin
                    - cmf_routing.redirect_route_admin
                    - nvbooster_starter.routecontainer_admin
            menu:
                label: Menu
                items:
                    - cmf_menu.menu_admin
                    - cmf_menu.node_admin
                    - nvbooster_starter.menuconnector_admin
            opcontent:
                label: One Page
                items:
                    - nvbooster_starter.opcontent_admin
                    - nvbooster_starter.opcontentsection_admin